name: cardapio5
description: "tentativa 5, usando flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  cupertino_icons: ^1.0.8
  intl: ^0.17.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1  # Adicionado para gerenciar ícones

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"  # Caminho da imagem do ícone

flutter:
  uses-material-design: true
  assets:
    - assets/images/dtudo_logo.png
